language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    compiler: gcc
    python: "3.7"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - BUILD_TYPE=Release
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libstdc++11
      - GTEST_VERSION=1.8.1

  - os: linux
    dist: xenial
    language: python
    compiler: gcc
    python: "3.7"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - BUILD_TYPE=Debug
      - CONAN_BUILD_TYPE=Debug
      - COMPILER_LIBCXX=libstdc++11
      - GTEST_VERSION=1.8.1

  - os: osx
    osx_image: xcode12.2
    language: cpp
    compiler: clang   
    env:
      - BUILD_TYPE=Release
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libc++
      - GTEST_VERSION=1.8.1
      - HOMEBREW_NO_AUTO_UPDATE=1
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
        - /usr/local/Homebrew

install: 
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then pip install conan; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install conan; fi
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

script:
  - g++ --version
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg JSONAdapterInterface/conanfile.py "JSONAdapterInterface/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    else
      conan export-pkg JSONAdapterInterface/conanfile.py "JSONAdapterInterface/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    fi
  - mkdir -p build
  - cd build
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan install ../JSONAdapterTestUtilities -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -e VERSION="${TRAVIS_TAG:1}";
    else
      conan install ../JSONAdapterTestUtilities -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -e VERSION="0.0.${TRAVIS_BUILD_NUMBER}";
    fi
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg ../JSONAdapterTestUtilities/conanfile.py "JSONAdapterTestUtilities/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION};
    else
      conan export-pkg ../JSONAdapterTestUtilities/conanfile.py "JSONAdapterTestUtilities/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION};
    fi
  - |
    if [ "$BUILD_TYPE" == "Release" ] || [ "$BUILD_TYPE" == "Debug" ]; then
      if [ -n "$TRAVIS_TAG" ]; then
        conan test ../test_package/conanfile.py JSONAdapterTestUtilities/${TRAVIS_TAG:1}@systelab/stable -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION};
      else
        conan test ../test_package/conanfile.py JSONAdapterTestUtilities/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION};
      fi
    fi
  - cd ..

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./ci/deploy.sh -v "${TRAVIS_TAG:1}"
  on:
    tags: true
